name: Foster Family Fun
favicon: null
layout_spectrum: 0.8
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6fdff'
    - '#383761'
    - '#e4dfe6'
    - '#a296a4'
    - '#69607b'
  brandStrength: 0
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: 2f16311a-5c5d-4218-b288-e91b55f2cc5b
    url: null
